# Generated by Django 5.1.3 on 2024-11-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('post_office_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(default='post_office_user', max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('branch_type', models.CharField(max_length=50)),
                ('delivery_status', models.CharField(max_length=50)),
                ('circle', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
