# Generated by Django 5.1.3 on 2024-11-28 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpai_app', '0003_remove_divisionaloffice_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('compliance_id', models.AutoField(primary_key=True, serialize=False)),
                ('compliance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_scores', to='gpai_app.postoffice')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cleanliness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_clean', models.BooleanField(blank=True, null=True)),
                ('cleanliness_status', models.CharField(blank=True, max_length=50, null=True)),
                ('waste_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gpai_app.postoffice')),
            ],
        ),
    ]
