# Generated by Django 5.1.3 on 2024-11-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpai_app', '0004_compliancescore_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='waste_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
