# Generated by Django 5.1.3 on 2024-12-02 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpai_app', '0007_utilitybill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign_Drive',
            fields=[
                ('campaign_drive_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_drive_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=65535, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_people_registered', models.PositiveIntegerField(default=0)),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='gpai_app.postoffice')),
            ],
        ),
    ]
