# Generated by Django 5.1.3 on 2024-12-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpai_app', '0008_campaign_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_drive',
            name='Venue',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
