# Generated by Django 5.1.3 on 2024-12-12 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpai_app', '0010_recyclingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('citizen_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('total_points', models.IntegerField(default=0)),
                ('role', models.CharField(default='citizen', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('recycle_score', models.IntegerField(default=0)),
                ('campaign_score', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpai_app.campaign_drive')),
                ('recycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpai_app.recyclingrequest')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpai_app.citizen')),
            ],
        ),
    ]
